export default {
	Inter_400Regular: "Inter_400Regular",
	Inter_500Medium: "Inter_500Medium",
	Inter_600SemiBold: "Inter_600SemiBold",
	Inter_700Bold: "Inter_700Bold",
	Inter_900Black: "Inter_900Black",
	jomhuria: "Jomhuria-Regular",
	poppins: "Poppins-Regular",
	Jomhuria_Regular: "Jomhuria-Regular",
	Poppins_Black: "Poppins-Black",
	Poppins_BlackItalic: "Poppins-BlackItalic",
	Poppins_Bold: "Poppins-Bold",
	Poppins_BoldItalic: "Poppins-BoldItalic",
	Poppins_ExtraBold: "Poppins-ExtraBold",
	Poppins_ExtraBoldItalic: "Poppins-ExtraBoldItalic",
	Poppins_ExtraLight: "Poppins-ExtraLight",
	Poppins_ExtraLightItalic: "Poppins-ExtraLightItalic",
	Poppins_Italic: "Poppins-Italic",
	Poppins_Light: "Poppins-Light",
	Poppins_LightItalic: "Poppins-LightItalic",
	Poppins_Medium: "Poppins-Medium",
	Poppins_MediumItalic: "Poppins-MediumItalic",
	Poppins_Regular: "Poppins-Regular",
	Poppins_SemiBold: "Poppins-SemiBold",
	Poppins_SemiBoldItalic: "Poppins-SemiBoldItalic",
	Poppins_Thin: "Poppins-Thin",
	Poppins_ThinItalic: "Poppins-ThinItalic"
};
